src/config/partnersList.js

Signed-off-by: Manank Patni <manank321@gmail.com>

Add bzx partner

---

src/config/partnersList.js

Signed-off-by: Manank Patni <manank321@gmail.com>

Add charged particles partner

---

src/config/partnersList.js

Signed-off-by: Manank Patni <manank321@gmail.com>

Add yam finance partnership

---

src/components/SharedStyling.js
src/pages/FAQ.js

- update the FAQ section of the epns website.

Feature update faq

---

src/components/SharedStyling.js
src/components/TimerItem.js
src/pages/FAQ.js

add new exchanges

---

src/components/EPNSChannelItems.js

Removed the last 2 channels

---

src/components/SharedStyling.js
src/pages/PressKit.js

1> Resolves the Issue of flex direction in tablet screen view in home page.
2> Resolves the Issue of images not loading in speaker events section in presskit page.

Resolved Issue of flex direction in tablet screen view

---

src/pages/Gov.js

- update the number of applications received and approved
- update the duration section

Update grants info

---

src/pages/FAQ.tsx

Fix: typos

---

src/components/PartnerChannels.tsx

reolves issue https://github.com/ethereum-push-notification-service/push-website/issues/154
RCA:
because of onscreen changes every time it make active as true or false,based active we were  changing width of Body component ,which makes change detect by onscreen(IIntersectionObserver) so it was going to infinite loop. to avoid this  width of Body should be static ,so currently made it 100%,if required we can make it to 85% (due this width variation no of lines of text differ for 85% 4 and for 100% 3 lines.
attaching screenshot of code for reference.

done changes for issue #154

---

src/pages/BlogItem.tsx

filtering current opened blog from the read more blogs section and added skeleton placeholder in blogs

filtering current opened blog from the read more blogs section and added skeleton placeholder

---

src/components/Schedules.tsx
src/helpers/ScheduleLists.ts

Schedule section is now displayed in slide fashion not an infinite loop.

Schedule infinte loop issue is fixed

---

docs/notifications/05-push-smart-contracts/03-PSC-Push-Contract-Addresses.mdx

Includes the following:
- Contract addresses updated 
- Categorized mainnet vs testnet contracts
- explorer links updated for specific chains
- Additional chains (zkEVM and arbitrum) included

fixed push-contract addresses

---

docs/notifications/03-showrunners-scaffold/03-Examples/07-Tutorial-Notification-Settings-With-Showrunners.mdx
docs/notifications/04-tutorials/08-Tutorial-Notification-Settings-With-Showrunners.mdx

This PR consist of a detailed tutorial on how to integrate notification settings with showrunners. Closes #449

Added notification settings tutorial X Showrunners

---

docs/video/01-Intro-Push-Video.mdx
docs/video/01-build/01-Develop-Get-Started.mdx
docs/video/01-build/03-Develop-Initiate-Video-Call.mdx
docs/video/01-build/05-Develop-Handling-Call-Retries.mdx
docs/video/03-Quickstart-Push-Video.mdx

- Update request > recipientAddress param to `string | string[]` 
- Add peerAddress param to `connect`, `disconnect` methods
- Fix typos

Update push video documentation

---

docs/chat/01-build/02-Develop-Initialize-User.mdx
docs/notifications/01-build/03-Develop-Initialize-User.mdx

docs: added docs for PushAPI intialization

---

docs/chat/01-build/02-Develop-Initialize-User.mdx
docs/chat/01-build/13-All-API-Calls.mdx
docs/chat/02-Quickstart-Push-Chat.mdx
docs/chat/03-ui-components/01-Integrate-Push-Chat.mdx
docs/chat/03-ui-components/Advanced/01-Integrate-Advanced-ChatUIProvider.mdx
docs/notifications/01-build/03-Develop-Initialize-User.mdx
docs/notifications/02-Quickstart-Push-Notification.mdx
docs/video/03-Quickstart-Push-Video.mdx

Push sdk now supports both ethersV5 and ethersV6

Ethers changes

---

docs/chat/01-build/12-Develop-Stream-Chat.mdx

This pull request addresses the **Issue #571** by enhancing the documentation for Stream Chat in the Push Website. The existing documentation was outdated, and this update brings clarity, correctness, and additional details to improve user understanding.
- Updated the Stream Chat overview section with clearer explanations.
- Refined code example for initializing and listening to Stream Chat events.
- Detailed parameters, subtypes, and default values for better comprehension.
- Highlighted the importance of listen events and when they are triggered.
This update aims to enhance user experience and understanding of Stream Chat in the Push SDK. Thank you for considering this pull request.
**Note:** This pull request will close issue #571 upon merging.

Stream Chat Documentation Update

---

docs/chat/01-build/05-Develop-Chat-Requests.mdx
docs/chat/01-build/08-Develop-Group-Requests.mdx
docs/roadmap/01-Push-Roadmap.mdx
sidebars.js

- Added unblock API to chat docs.
- Added Reject Group Joining Request API to chat docs.
- Edited param for block API in chat

update chat requests & group request docs

---

docs/chat/01-build/07-Develop-Create-Group.mdx
docs/chat/01-build/10-Develop-Conditional-Rule-For-Groups.mdx

docs: add guild group examples

---

docs/chat/01-build/05-Develop-Chat-Requests.mdx
docs/chat/01-build/09-Develop-Group-Permissions.mdx
docs/chat/01-build/11-Develop-Manage-Group.mdx
docs/chat/01-build/12-Develop-Stream-Chat.mdx

docs:  added new chat methods

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml

This pull request adds a feature request template to improve the features of the existing website.
- Created feature_request.yml
- Structured fields for users to fill out when reporting a bug.
- Included instructions for each field.
This template aims to streamline feature request by providing a clear format for users to follow.
This PR fixes #648 if merged.

Add issue template for feature request. 

---

docs/video/01-build/06-Develop-Request-Video-Call.mdx
docs/video/01-build/07-Develop-Manage-Video-Call.mdx

docs: add expected responses in video

---

docs/chat/01-build/12-Develop-Stream-Chat.mdx
docs/notifications/01-build/15-Develop-Stream-Notifications.mdx
docs/video/01-build/04-Develop-Stream-Video.mdx

docs: add reinit stream and stream info docs

---

docs/notifications/03-showrunners-scaffold/03-Examples/08-Showrunner-Example-Btc-Tracker.mdx
docs/notifications/03-showrunners-scaffold/03-Examples/08-Showrunner-Example-Time-Interval-Price-Alerts.mdx
docs/notifications/03-showrunners-scaffold/03-Examples/09-Showrunner-Example-Price-Tracker.mdx

This PR consists updated documentation for BTC ticker channel which solves the below cases. 
i) What happens when time is triggered but not percentage?
ii) What happens if a user opts-in, opts-out and then again after several days opt-in?
iii) What happens if someone changes their time-interval settings?
Closes #686

Btc ticker example

---

src/components/DocsHub/index.tsx
src/components/DocsHub/styles.css
src/components/NewMarqueeAnimation.tsx
src/config/globals.js
src/css/SharedStyling.js
src/css/custom.css
src/pages/home.tsx
src/segments/Header.tsx

Reverts ethereum-push-notification-service/push-website#711

Revert "Remove static horizontal padding from all sections of homepage to globals page"

---

.gitignore
docs/notifications/01-build/10-Develop-Fetch-Notifications.mdx

docs: added fetch channel notifications method

---

docs/notifications/04-showrunners-scaffold/03-Examples/03-Showrunner-Example-Service-Based-Trigger.mdx
docs/notifications/04-showrunners-scaffold/03-Examples/04-Showrunner-Example-Offchain-Web2-Based-Trigger.mdx
docs/notifications/04-showrunners-scaffold/03-Examples/06-Showrunner-Example-Advance-Oasis-Based-Trigger.mdx

fix: broken links in showrunners docs

---

src/components/DocsHub/styles.css
src/theme/Navbar/Content/index.js

- When you inspect or toggle in the docs section, it returns an error page
- Docs has the side table of content scattered in localhost

Fix Docs Issue

---

src/components/DocsHub/styles.css

Fix Docs Width on LG screens
